# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - release/*
    - develop
    - master
  tags:
    include:
    - v*

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  solutionFile: PamSharp.sln
  buildConfiguration: Release

jobs:
- job: prepare
  steps:
  - task: UseGitVersion@5
    displayName: 'GitVersion'
    inputs:
      versionSpec: '5.0.2-beta1.130'
      includePrerelease: true
      updateAssemblyInfo: false
    env:
      BUILD_BUILDNUMBER: $(GitVersion.FullSemVer)

- job: pack
  dependsOn: prepare
  condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: pack
      arguments: $(solutionFile) --output $(Build.ArtifactStagingDirectory) --include-symbols /p:Configuration=$(buildConfiguration) /p:Version=$(build.buildNumber) --verbosity Minimal
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: packages

- job: build
  dependsOn: prepare
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(solutionFile)
      arguments: '/p:Configuration=$(buildConfiguration) /p:Version=$(build.buildNumber) --verbosity Minimal'

- job: test
  dependsOn: prepare
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Debug'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'test/FubarDev.PamSharp.Tests/FubarDev.PamSharp.Tests.csproj'
